services:
    seerr:
        image: ghcr.io/seerr-team/seerr:latest
        container_name: seerr
        restart: unless-stopped
        ports:
            - "5055:5055"
        volumes:
            - /opt/docker-data/seerr/config:/app/config

    cli_debrid:
        image: godver3/cli_debrid:latest
        container_name: cli_debrid
        restart: unless-stopped
        ports:
            - "5000:5000"
        volumes:
            - /opt/docker-data/seerr/cli_debrid/config:/app/config
            - /opt/docker-data/seerr/cli_debrid/db_content:/app/db_content
            - /opt/docker-data/seerr/cli_debrid/logs:/app/logs
            - /opt/docker-data/seerr/cli_debrid/autobase_storage_v4:/app/autobase_storage_v4
            # The vital link! The exact same volume mapped to the exact same path.
            - /opt/docker-data/media:/media
        depends_on:
            - seerr
