version: "3.9"
services:
  livesync-cli:
    build:
      context: https://github.com/vrtmrz/obsidian-livesync.git#main
      dockerfile: src/apps/cli/Dockerfile
    image: obsidian-livesync-cli:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/lw/obsidian/Memex:/vault:rw
      - /opt/docker-data/obsidian-livesync-cli/data:/data:rw
    command: daemon /data --settings /data/settings.json --vault /vault
