services:
    copyparty:
        image: copyparty/ac:latest
        container_name: copyparty
        restart: unless-stopped
        environment:
            # We map this container to the same UID/GID as the `lw` user on the host
            - PUID=1000
            - PGID=100
        volumes:
            - /opt/docker-data/copyparty/config:/cfg
            - /home/lw:/home/lw
        ports:
            - "3923:3923"
        command:
            - "-p"
            - "3923"
            - "-v"
            - "/home/lw::A"
            - "-c"
            - "/cfg/copyparty.conf"
