services:
    copyparty:
        image: copyparty/ac:latest
        container_name: copyparty
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=100
        volumes:
            - /opt/docker-data/copyparty/config/copyparty.conf:/cfg/copyparty.conf:ro
            - /home/lw:/home/lw
        ports:
            - "3923:3923"
